language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

sudo: required

dist: xenial

env:
  - PIP_USE_MIRRORS=true

install:
  - python setup.py install
  - pip install coveralls

script:
  - python setup.py test
  - coverage run --source=pyencourage setup.py test

after_success:
  - coveralls
