site_name: pyencourage
theme: mkdocs
repo_url: https://github.com/seantibor/pyencourage
site_description: One-line programmer encouragement (encouragement-as-a-service)
site_author: Sean Tibor
site_dir: website
nav:
    - 'Home': 'index.md'
    - 'Install': 'install.md'
    - 'API Reference': 'api.md'
